### ISSUE TITLE
[DEV:aurelia] Error: AUR0153: Element  has already been registered

### ISSUE THREAD

**Issue by ivanbacher** [aurelia/aurelia#1951]
I have a repo with the following structure:

```
- dialog
  - test-element-one.html
    - test-element-two.html  
```

The `dialog` adds `test-element-one.html` to the view and `test-element-one.html` adds `test-element-two.html` to the view.

However, each time `test-element-two` is added to the view this warning/error pops up

```
[DEV:aurelia] Error: AUR0153: Element test-element-two has already been registered.
```

Is it safe to ignore it?

Here is a link to the sample repo:
https://github.com/ivanbacher/au2-component-test

**Comment by bigopon** [comment]
If we want cleanliness, it shouldnt be there. Ill investigate, thanks for the repro @ivanbacher

**Comment by ekzobrain** [comment]
Currently this behaves very annoying, especially with Router. For example I have two components which register the same dependencies (partially intersecting). I get this error every time I navigate from one component to another. Just did not have time to post an issue yet.

**Comment by bigopon** [comment]
@ekzobrain originally it wasnt logging anything, and I dont think its right. If theres something done repeatedly unnecessarily, it likely needs a ttweak. But I wasnt getting that info so added a warning with a hope that we would see this pops up in apps, which we do now.

**Comment by ivanbacher** [comment]
Thanks @bigopon.

I also noticed the warning message pop up when a change is made within the code and the webpack hot module replacement is activated. Sometimes this even causes the AU2 app to freeze. Seems to get caught in a reloading loop as the waring messages are continuously printed in the console.  This might be webpacks fault thought. I will investigate a bit further.

**Comment by bigopon** [comment]
This should be resolved in the latest dev version, can you try that? Example of it working properly without wrong warning is here https://stackblitz.com/edit/github-plzk4x?file=src%2Ftest-element-one.html

**Comment by bigopon** [comment]
> Thanks @bigopon.
> 
> I also noticed the warning message pop up when a change is made within the code and the webpack hot module replacement is activated. Sometimes this even causes the AU2 app to freeze. Seems to get caught in a reloading loop as the warning messages are continuously printed in the console. This might be webpacks fault thought. I will investigate a bit further.

Yes, there will need to be some tweak in hot module replacement, since even when we unmount the old component, we didn't de-register the old component and thus it'll warn. This is the final point preventing us from throwing when there's a duplicate registration.
In the mean time, please help report if you run into those warnings again, the target is we want to throw when there's a duplicate registration for resources.

**Comment by bigopon** [comment]
This is now resolved in dev & latest versions. Example https://stackblitz.com/edit/github-plzk4x

**Comment by bigopon** [comment]
Thanks @ivanbacher

**Comment by glyad** [comment]
I'm still experiencing the same behavior working with latest versions of Aurelia both using Vite and Webpack

**Comment by estaylorco** [comment]
I, too, am experiencing this problem (the AUR0153 error), even with a dry-run ```npx makes aurelia``` non-typescript app (with routing).  This is true of both **latest** and **dev** installs.
