### ISSUE TITLE
sass not working as expected

### ISSUE THREAD

**Issue by nnscr** [aurelia/aurelia#776]
# 🐛 Bug Report
After setting up a new aurelia 2 project using `npx makes aurelia` I'd expect to be able to change `my-app.css` to `my-app.scss` to use scss.

## 🤔 Expected Behavior
- Install `node-sass` and `sass-loader`, add a webpack rule for that (`{ test: /\.scss$/i, use: ["css-loader", "sass-loader"] }`)
- Add a <module>.scss file
- scss file should be compiled

## 😯 Current Behavior
scss does not get compiled and is passed to the browser as-is.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | aurelia@0.6.0-dev.201911180622 
| Language         |
| Browser          |
| Bundler          | webpack@4.41.2
| Operating System |
| NPM/Node/Yarn    |

**Comment by 3cp** [comment]
I am slowly working on a branch in my limited spare time for sass/less and various unit tests setup. Will be ready in a week or two.

You can target the branch now with `npx makes aurelia/new#tests`. It's not fully tested.

**Comment by nnscr** [comment]
Thank you very much, that sounds promising. I've tested your branch, but again I get the scss code as it is in the browser without compilation. Is there already some documentation on this topic? Or should I wait a week before playing around with aurelia 2 if sass is a feature that I really need?

(my setup: ` npx makes aurelia new-project-name -s typescript,shadow-dom-open,sass,no-unit-tests `)

**Comment by 3cp** [comment]
Thx. I can see there are multiple problems.

The biggest problem. Our shadow dom css setup doesn't work. We use `!!raw-loader!` to bypass webpack config for shadow dom css, but this doesn't work with scss or less which needs preprocessing. We need to remove `!!raw-loader!`, but use `issuer` in webpack.config to use `style-loader` for css import from js file, and skip `style-loader` for css import from html file. cc @EisenbergEffect

**Comment by 3cp** [comment]
I have merged untested branch to `aurelia/new` for the css setup fix.

The webpack-loader fix will be in coming daily dev release.

**Comment by 3cp** [comment]
@EisenbergEffect my fix still has a hole.

For shadow-dom app, it now uses `issuer` to separate css importing from js or html. It uses `style-loader` when user imports css from js file, or uses `to-string-loader` to support shadow-dom processing when user (actually convention processed html) imports css from html file.

But with your coming work, we need to support per file css config. While user app may turn off shadow-dom (which results no `issuer` in webpack config), 3rd-party npm packages can have shadow-dom turned on in its html module. Our webpack config is not flexible enough to support this mixed usage.

This is difficult for Aurelia 2 plugin projects, as they need to be compiled into bundler agnostic fashion. At the same time, the compiled html module needs to pack enough information on whether the bundler should load css into HTML head. Let me to know if you have some solution.

**Comment by nnscr** [comment]
Thanks for your time and looking into this. Do I understand correctly that you bypass webpack config for the module specific css files? Will we still have an option to configure our own loaders? We're using another pre processor before passing our files to sass and it would be a shame if we couldn't do that anymore.

**Comment by 3cp** [comment]
Yes. What I removed is default css module prefix`!!raw-loader!` from webpack-loader. That `!!raw-loader!` bypassed everything in webpack config.

The skeleton now config scss/less/css with two lines, one with  issuer from js/ts, another one with issuer from html. The second one is what applied to css resources loaded from your html template. You can modify loader chain there.

**Comment by 3cp** [comment]
You need to wait for the merge of that webpack-loader PR. Otherwise the updated skeleton wouldn't work.
